server:
 port: 9090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: bookuser
    password: password
    driverClassName: org.postgresql.Driver
  flyway:
   enabled: true